# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Github_RN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Github_RN
# Umeng公共基础
pod 'UMCCommon'
pod 'UMCSecurityPlugins'
pod 'UMCCommonLog'

# 统计
pod 'UMCAnalytics'

end
